windows_container:
  image: cirrusci/windowsservercore:2019

task:
  env:
    CIRRUS_SHELL: powershell
  scoop_install_script: |
    iwr -useb 'https://raw.githubusercontent.com/ScoopInstaller/Install/a90548e01abe99c9211e83c5fad3693ecf4227c2/install.ps1' | iex
    Write-Host "NEWPATH=$env:PATH" >> $env:CIRRUS_ENV
    Write-Host $env:Path
    scoop which scoop
    scoop install 7zip innounp git
    scoop config SCOOP_REPO 'https://github.com/Ash258/Scoop-Core'
    scoop update
    scoop status
    scoop checkup
  path_echo_debug_script: |
    Write-Host 'Trying $CIRRUS_ENV'
    Write-Host $CIRRUS_ENV
    Write-Host 'Trying $env:CIRRUS_ENV'
    Write-Host $env:CIRRUS_ENV
    Write-Host 'Trying $env:Path'
    Write-Host $env:Path
    Write-Host 'Trying $env:NEWPATH'
    Write-Host $env:NEWPATH
